version: '3.5'

services:

  web:
    image: laemmi/php-ci
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./.docker/apache2/log:/var/log/apache2
      - ./.docker/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./:/var/www/html:delegated

  mysql:
    image: mariadb:10.3
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3380:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver_opts:
      type: none
      device: $PWD/.docker/mysql/data
      o: bind

networks:
  frontend:
  backend: