version: '3'

services:
  mysql:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql:cached
  php:
    image: laemmi/php-ci
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./.docker/apache2/log:/var/log/apache2:cached
      - ./.docker/apache2/sites-enabled:/etc/apache2/sites-enabled:cached
      - ./:/var/www/html:cached