version: '3.5'

services:

  web:
    build:
      context: ./.docker/web
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated

  mysql:
    build:
      context: ./.docker/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3380:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver_opts:
      type: none
      device: $PWD/.docker/mysql/data
      o: bind

networks:
  frontend:
  backend: